'use client';

/**
 * Report Details Page
 *
 * Detail view for a report with delete option.
 * Reports are generated by the system; user can view and delete.
 *
 * Backend: GET /cybersecurity/reports/{id}
 *          DELETE /cybersecurity/reports/{id}
 */

import { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { useReports } from '@/modules/cybersecurity/hooks/discovery/use-reports';
import { useFindings } from '@/modules/cybersecurity/hooks/discovery/use-findings';
import {
  getReportTypeLabel,
  getReportFormatLabel,
  type Report,
} from '@/modules/cybersecurity/schemas/discovery/reports.schemas';
import {
  SEVERITY_COLORS,
  getSeverityLabel,
  SeverityEnum,
} from '@/modules/cybersecurity/schemas/discovery/findings.schemas';
import { buildAiFixExport } from '@/modules/cybersecurity/utils/report-ai-export.utils';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/modules/shadcnui/components/ui/card';
import { Button } from '@/modules/shadcnui/components/ui/button';
import { Input } from '@/modules/shadcnui/components/ui/input';
import { Alert, AlertDescription } from '@/modules/shadcnui/components/ui/alert';
import { Loader2, ArrowLeft, FileText, Trash2, Sparkles, Check, ExternalLink } from 'lucide-react';
import Link from 'next/link';
import { ExportButton } from '@/modules/cybersecurity/components/shared/export-button';
import { REPORT_ENDPOINTS } from '@/modules/cybersecurity/utils/api.endpoints';

export default function ReportDetailsPage() {
  const params = useParams();
  const router = useRouter();
  const id = parseInt(params.id as string);
  const {
    fetchReport,
    deleteReport,
    isLoading,
    error: storeError,
  } = useReports();
  // Findings rendered in-UI come from the report's scan job (append-only, so this IS the snapshot).
  const { findings, fetchFindings } = useFindings();

  // Local state for the fetched item
  const [item, setItem] = useState<Report | null>(null);
  const [isDeleting, setIsDeleting] = useState(false);
  const [deleteConfirm, setDeleteConfirm] = useState('');
  // Transient "copied" feedback for the per-finding "Copy AI Fix" and the report-wide "Export for AI".
  const [aiExported, setAiExported] = useState(false);
  const [copiedScriptId, setCopiedScriptId] = useState<number | null>(null);

  // Fetch item on mount
  useEffect(() => {
    const load = async () => {
      const data = await fetchReport(id);
      if (data) {
        setItem(data);
      }
    };
    load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [id]);

  // Once the report is loaded, pull its scan job's findings for the in-UI breakdown.
  // Why guard on scan_job_id: the findings endpoint filters by scan_job_id; a target-level
  // report (no scan_job_id) can't be filtered, so we skip the list and show a note instead.
  useEffect(() => {
    if (item?.scan_job_id) {
      fetchFindings({ scan_job_id: item.scan_job_id });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [item?.scan_job_id]);

  // Copy a single finding's scanner remediation script to the clipboard (assetmanager pattern).
  const handleCopyScript = (findingId: number, script: string) => {
    navigator.clipboard.writeText(script);
    setCopiedScriptId(findingId);
    setTimeout(() => setCopiedScriptId(null), 2000);
  };

  // Build one combined AI-fix markdown for ALL findings, copy it + offer a .md download.
  const handleAiExport = () => {
    if (!item) return;
    const markdown = buildAiFixExport(item.name, findings);
    navigator.clipboard.writeText(markdown);
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = `${item.name}-ai-fixes.md`;
    anchor.click();
    URL.revokeObjectURL(url);
    setAiExported(true);
    setTimeout(() => setAiExported(false), 2000);
  };

  // Handle delete
  const handleDelete = async () => {
    setIsDeleting(true);
    const success = await deleteReport(id);
    setIsDeleting(false);
    if (success) {
      router.push('/reports');
    }
  };

  // ==========================================
  // Render
  // ==========================================

  if (isLoading && !item) {
    return (
      <div className="flex items-center justify-center p-8">
        <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  if (!item) {
    return (
      <div className="max-w-4xl mx-auto space-y-6">
        <Alert variant="destructive">
          <AlertDescription>Report not found.</AlertDescription>
        </Alert>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Header */}
      <div>
        <Link href="/reports">
          <Button variant="ghost" size="sm" className="mb-4">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Reports
          </Button>
        </Link>
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <FileText className="h-8 w-8 text-muted-foreground" />
            <div>
              <h1 className="text-3xl font-bold tracking-tight">{item.name}</h1>
              <p className="text-muted-foreground">
                {getReportTypeLabel(item.report_type)} &middot; {getReportFormatLabel(item.format)}
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            {/* Export every finding as one AI-fix prompt (copy + .md download) */}
            {item.scan_job_id && findings.length > 0 && (
              <Button variant="outline" onClick={handleAiExport}>
                {aiExported ? (
                  <><Check className="mr-2 h-4 w-4" /> Copied</>
                ) : (
                  <><Sparkles className="mr-2 h-4 w-4" /> Export for AI</>
                )}
              </Button>
            )}
            {/* Export as branded PDF */}
            <ExportButton
              exportUrl={REPORT_ENDPOINTS.EXPORT(id)}
              fileName={item.name}
              pdfOnly
            />
          </div>
        </div>
      </div>

      {storeError && (
        <Alert variant="destructive">
          <AlertDescription>{storeError}</AlertDescription>
        </Alert>
      )}

      {/* Card 1: Report Info */}
      <Card>
        <CardHeader>
          <CardTitle>Report Info</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 gap-4">
            <div><p className="text-sm text-muted-foreground">Name</p><p className="font-medium">{item.name}</p></div>
            <div><p className="text-sm text-muted-foreground">Report Type</p><p className="font-medium">{getReportTypeLabel(item.report_type)}</p></div>
            <div><p className="text-sm text-muted-foreground">Format</p><p className="font-medium">{getReportFormatLabel(item.format)}</p></div>
            <div><p className="text-sm text-muted-foreground">Generated At</p><p className="font-medium">{new Date(item.generated_at).toLocaleString()}</p></div>
            <div><p className="text-sm text-muted-foreground">Generated By</p><p className="font-medium">{item.generated_by ?? '—'}</p></div>
            <div><p className="text-sm text-muted-foreground">Scan Job</p><p className="font-medium">{item.scan_job_id ? `#${item.scan_job_id}` : '—'}</p></div>
            <div><p className="text-sm text-muted-foreground">Target</p><p className="font-medium">{item.target_name || `#${item.target_id}`}</p></div>
            <div><p className="text-sm text-muted-foreground">Created</p><p className="font-medium">{new Date(item.created_at).toLocaleString()}</p></div>
          </div>
        </CardContent>
      </Card>

      {/* Card 2: Summary (only if summary present) */}
      {item.summary && (
        <Card>
          <CardHeader>
            <CardTitle>Summary</CardTitle>
          </CardHeader>
          <CardContent>
            <p>{item.summary}</p>
          </CardContent>
        </Card>
      )}

      {/* Severity summary tiles — counts come from the report record (reliable, snapshot). */}
      <div className="grid grid-cols-3 gap-3 sm:grid-cols-6">
        <div className="rounded-lg border p-4">
          <p className="text-xs text-muted-foreground">Total</p>
          <p className="text-2xl font-bold">{item.total_findings}</p>
        </div>
        {([
          ['Critical', item.critical_count, 'text-red-600'],
          ['High', item.high_count, 'text-orange-500'],
          ['Medium', item.medium_count, 'text-yellow-500'],
          ['Low', item.low_count, 'text-blue-400'],
          ['Info', item.info_count, 'text-gray-400'],
        ] as const).map(([label, count, color]) => (
          <div key={label} className="rounded-lg border p-4">
            <p className="text-xs text-muted-foreground">{label}</p>
            <p className={`text-2xl font-bold ${color}`}>{count}</p>
          </div>
        ))}
      </div>

      {/* Findings breakdown — grouped by severity (the in-UI report body). */}
      {!item.scan_job_id ? (
        // Target-level report: the findings endpoint can only filter by scan_job_id, so there is
        // no single scan to render. Counts above still apply; per-scan reports show the breakdown.
        <Alert>
          <AlertDescription>
            This report aggregates multiple scans. Open a per-scan report to see the finding breakdown here.
          </AlertDescription>
        </Alert>
      ) : findings.length === 0 ? (
        <Card>
          <CardContent className="py-8 text-center text-muted-foreground">
            No findings recorded for this scan.
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-6">
          {/* Iterate severities in canonical order (critical → info); skip empty groups. */}
          {SeverityEnum.options.map((sev) => {
            const group = findings.filter((f) => f.severity === sev);
            if (group.length === 0) return null;
            return (
              <div key={sev} className="space-y-3">
                <h2 className="text-lg font-semibold">
                  {getSeverityLabel(sev)} ({group.length})
                </h2>
                {group.map((f) => (
                  <Card key={f.id}>
                    <CardHeader>
                      <CardTitle className="flex items-start justify-between gap-2 text-base">
                        <span>{f.title}</span>
                        <span className={`shrink-0 inline-block rounded px-2 py-0.5 text-xs font-medium ${SEVERITY_COLORS[f.severity]}`}>
                          {getSeverityLabel(f.severity)}
                        </span>
                      </CardTitle>
                    </CardHeader>
                    <CardContent className="space-y-3 text-sm">
                      <p>{f.description}</p>

                      {f.evidence && (
                        <div>
                          <p className="mb-1 text-xs text-muted-foreground">Evidence</p>
                          <pre className="overflow-x-auto whitespace-pre-wrap rounded bg-muted p-3 text-xs"><code>{f.evidence}</code></pre>
                        </div>
                      )}

                      {f.remediation && (
                        <div>
                          <p className="mb-1 text-xs text-muted-foreground">Remediation</p>
                          <p>{f.remediation}</p>
                        </div>
                      )}

                      {f.remediation_script && (
                        <div>
                          <p className="mb-1 text-xs text-muted-foreground">Fix command</p>
                          <pre className="overflow-x-auto rounded bg-muted p-3 text-xs"><code>{f.remediation_script}</code></pre>
                        </div>
                      )}

                      <div className="flex items-center gap-2 pt-1">
                        {f.ai_fix_prompt && (
                          <Button variant="outline" size="sm" onClick={() => handleCopyScript(f.id, f.ai_fix_prompt!)}>
                            {copiedScriptId === f.id ? (
                              <><Check className="mr-2 h-3.5 w-3.5" /> Copied</>
                            ) : (
                              <><Sparkles className="mr-2 h-3.5 w-3.5" /> Copy AI Fix</>
                            )}
                          </Button>
                        )}
                        <Link href={`/findings/${f.id}`}>
                          <Button variant="ghost" size="sm">
                            <ExternalLink className="mr-2 h-3.5 w-3.5" /> Details
                          </Button>
                        </Link>
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </div>
            );
          })}
        </div>
      )}

      {/* Delete section */}
      <Card className="border-destructive">
        <CardHeader>
          <CardTitle className="text-destructive">Danger Zone</CardTitle>
          <CardDescription>
            Permanently delete this report. This action cannot be undone.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <p className="text-sm text-muted-foreground">
            Type <span className="font-mono font-bold">{item.name}</span> to confirm deletion.
          </p>
          <Input
            value={deleteConfirm}
            onChange={(e) => setDeleteConfirm(e.target.value)}
            placeholder={item.name}
            disabled={isDeleting}
          />
          <Button
            variant="destructive"
            onClick={handleDelete}
            disabled={deleteConfirm !== item.name || isDeleting}
          >
            {isDeleting ? (
              <><Loader2 className="mr-2 h-4 w-4 animate-spin" /> Deleting...</>
            ) : (
              <><Trash2 className="mr-2 h-4 w-4" /> Delete Report</>
            )}
          </Button>
        </CardContent>
      </Card>
    </div>
  );
}
