'use client';

/**
 * Report Details Page
 *
 * Detail view for a report with delete option.
 * Reports are generated by the system; user can view and delete.
 *
 * Backend: GET /cybersecurity/reports/{id}
 *          DELETE /cybersecurity/reports/{id}
 */

import { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { useReports } from '@/modules/cybersecurity/hooks/discovery/use-reports';
import {
  getReportTypeLabel,
  getReportFormatLabel,
  type Report,
} from '@/modules/cybersecurity/schemas/discovery/reports.schemas';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/modules/shadcnui/components/ui/card';
import { Button } from '@/modules/shadcnui/components/ui/button';
import { Input } from '@/modules/shadcnui/components/ui/input';
import { Alert, AlertDescription } from '@/modules/shadcnui/components/ui/alert';
import { Loader2, ArrowLeft, FileText, Trash2 } from 'lucide-react';
import Link from 'next/link';

export default function ReportDetailsPage() {
  const params = useParams();
  const router = useRouter();
  const id = parseInt(params.id as string);
  const {
    fetchReport,
    deleteReport,
    isLoading,
    error: storeError,
  } = useReports();

  // Local state for the fetched item
  const [item, setItem] = useState<Report | null>(null);
  const [isDeleting, setIsDeleting] = useState(false);
  const [deleteConfirm, setDeleteConfirm] = useState('');

  // Fetch item on mount
  useEffect(() => {
    const load = async () => {
      const data = await fetchReport(id);
      if (data) {
        setItem(data);
      }
    };
    load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [id]);

  // Handle delete
  const handleDelete = async () => {
    setIsDeleting(true);
    const success = await deleteReport(id);
    setIsDeleting(false);
    if (success) {
      router.push('/reports');
    }
  };

  // ==========================================
  // Render
  // ==========================================

  if (isLoading && !item) {
    return (
      <div className="flex items-center justify-center p-8">
        <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  if (!item) {
    return (
      <div className="max-w-4xl mx-auto space-y-6">
        <Alert variant="destructive">
          <AlertDescription>Report not found.</AlertDescription>
        </Alert>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Header */}
      <div>
        <Link href="/reports">
          <Button variant="ghost" size="sm" className="mb-4">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Reports
          </Button>
        </Link>
        <div className="flex items-center gap-3">
          <FileText className="h-8 w-8 text-muted-foreground" />
          <div>
            <h1 className="text-3xl font-bold tracking-tight">{item.name}</h1>
            <p className="text-muted-foreground">
              {getReportTypeLabel(item.report_type)} &middot; {getReportFormatLabel(item.format)}
            </p>
          </div>
        </div>
      </div>

      {storeError && (
        <Alert variant="destructive">
          <AlertDescription>{storeError}</AlertDescription>
        </Alert>
      )}

      {/* Card 1: Report Info */}
      <Card>
        <CardHeader>
          <CardTitle>Report Info</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 gap-4">
            <div><p className="text-sm text-muted-foreground">Name</p><p className="font-medium">{item.name}</p></div>
            <div><p className="text-sm text-muted-foreground">Report Type</p><p className="font-medium">{getReportTypeLabel(item.report_type)}</p></div>
            <div><p className="text-sm text-muted-foreground">Format</p><p className="font-medium">{getReportFormatLabel(item.format)}</p></div>
            <div><p className="text-sm text-muted-foreground">Generated At</p><p className="font-medium">{new Date(item.generated_at).toLocaleString()}</p></div>
            <div><p className="text-sm text-muted-foreground">Generated By</p><p className="font-medium">{item.generated_by ?? '—'}</p></div>
            <div><p className="text-sm text-muted-foreground">Scan Job ID</p><p className="font-medium">{item.scan_job_id ?? '—'}</p></div>
            <div><p className="text-sm text-muted-foreground">Target ID</p><p className="font-medium">{item.target_id}</p></div>
            <div><p className="text-sm text-muted-foreground">Created</p><p className="font-medium">{new Date(item.created_at).toLocaleString()}</p></div>
          </div>
        </CardContent>
      </Card>

      {/* Card 2: Summary (only if summary present) */}
      {item.summary && (
        <Card>
          <CardHeader>
            <CardTitle>Summary</CardTitle>
          </CardHeader>
          <CardContent>
            <p>{item.summary}</p>
          </CardContent>
        </Card>
      )}

      {/* Card 3: Statistics */}
      <Card>
        <CardHeader>
          <CardTitle>Statistics</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          <div>
            <p className="text-sm text-muted-foreground mb-1">Total Findings</p>
            <p className="font-medium">{item.total_findings}</p>
          </div>
          <div>
            <p className="text-sm text-muted-foreground mb-2">Severity Breakdown</p>
            <div className="flex flex-wrap gap-2">
              <span className="inline-block px-2 py-0.5 rounded text-xs font-medium bg-red-600 text-white">Critical: {item.critical_count}</span>
              <span className="inline-block px-2 py-0.5 rounded text-xs font-medium bg-orange-500 text-white">High: {item.high_count}</span>
              <span className="inline-block px-2 py-0.5 rounded text-xs font-medium bg-yellow-500 text-black">Medium: {item.medium_count}</span>
              <span className="inline-block px-2 py-0.5 rounded text-xs font-medium bg-blue-400 text-white">Low: {item.low_count}</span>
              <span className="inline-block px-2 py-0.5 rounded text-xs font-medium bg-gray-400 text-white">Info: {item.info_count}</span>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Card 4: Content (only if content present) */}
      {item.content && (
        <Card>
          <CardHeader>
            <CardTitle>Content</CardTitle>
          </CardHeader>
          <CardContent>
            <pre className="bg-muted p-4 rounded overflow-x-auto max-h-96"><code>{item.content}</code></pre>
          </CardContent>
        </Card>
      )}

      {/* Delete section */}
      <Card className="border-destructive">
        <CardHeader>
          <CardTitle className="text-destructive">Danger Zone</CardTitle>
          <CardDescription>
            Permanently delete this report. This action cannot be undone.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <p className="text-sm text-muted-foreground">
            Type <span className="font-mono font-bold">{item.name}</span> to confirm deletion.
          </p>
          <Input
            value={deleteConfirm}
            onChange={(e) => setDeleteConfirm(e.target.value)}
            placeholder={item.name}
            disabled={isDeleting}
          />
          <Button
            variant="destructive"
            onClick={handleDelete}
            disabled={deleteConfirm !== item.name || isDeleting}
          >
            {isDeleting ? (
              <><Loader2 className="mr-2 h-4 w-4 animate-spin" /> Deleting...</>
            ) : (
              <><Trash2 className="mr-2 h-4 w-4" /> Delete Report</>
            )}
          </Button>
        </CardContent>
      </Card>
    </div>
  );
}
