"""Add feedback table

Revision ID: 64cfb7d9d667
Revises: 5df0fe077132
Create Date: 2026-06-21 01:44:42.381438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64cfb7d9d667'
down_revision: Union[str, Sequence[str], None] = '5df0fe077132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cybersecurity_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('page_url', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cybersecurity_feedback_id'), 'cybersecurity_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_cybersecurity_feedback_organization_id'), 'cybersecurity_feedback', ['organization_id'], unique=False)
    op.create_index('ix_feedback_created_by', 'cybersecurity_feedback', ['created_by'], unique=False)
    op.create_index('ix_feedback_status', 'cybersecurity_feedback', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feedback_status', table_name='cybersecurity_feedback')
    op.drop_index('ix_feedback_created_by', table_name='cybersecurity_feedback')
    op.drop_index(op.f('ix_cybersecurity_feedback_organization_id'), table_name='cybersecurity_feedback')
    op.drop_index(op.f('ix_cybersecurity_feedback_id'), table_name='cybersecurity_feedback')
    op.drop_table('cybersecurity_feedback')
    # ### end Alembic commands ###
