"""Rename feedback indexes with table prefix

Revision ID: a032b2c1400a
Revises: 64cfb7d9d667
Create Date: 2026-06-21 11:43:07.891847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a032b2c1400a'
down_revision: Union[str, Sequence[str], None] = '64cfb7d9d667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_created_by'), table_name='cybersecurity_feedback')
    op.drop_index(op.f('ix_feedback_status'), table_name='cybersecurity_feedback')
    op.create_index('ix_cybersecurity_feedback_created_by', 'cybersecurity_feedback', ['created_by'], unique=False)
    op.create_index('ix_cybersecurity_feedback_status', 'cybersecurity_feedback', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cybersecurity_feedback_status', table_name='cybersecurity_feedback')
    op.drop_index('ix_cybersecurity_feedback_created_by', table_name='cybersecurity_feedback')
    op.create_index(op.f('ix_feedback_status'), 'cybersecurity_feedback', ['status'], unique=False)
    op.create_index(op.f('ix_feedback_created_by'), 'cybersecurity_feedback', ['created_by'], unique=False)
    # ### end Alembic commands ###
